# Site settings
title: "Early Spring Excursion"
description: "Your Mysterious China Tour"
url: "http://earlyspringexcursion.com"
author: "Luche & Johanna"
exclude: [Rakefile]

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Links
links:
  - title: "Early Spring Excursion"
    url: http://earlyspringexcursion.com
  - title: "rss"
    url: /feed.xml

plugins:
  - jekyll-seo-tag
