# Site settings
title: "Early Spring Excursion"
description: ""
baseurl: ""
url: "http://earlyspringexcursion.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# Links
links:
  - title: "Early Spring Excursion"
    url: http://earlyspringexcursion.github.io
  - title: "rss"
    url: /feed.xml

plugins:
  - jekyll-seo-tag
  - jekyll-polyglot

languages: ["en", "fr", "cn"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true